// PVP spell cards data - mirror-duel style
export const SPELLS = [
  { id: 'sp_t4_1', name: '帽子戏法(4)', tier: 4, description: '使1个随从变为8/8', type: 'spell' },
  { id: 'sp_t4_2', name: '头脑风暴(4)', tier: 4, description: '获得4点经验', type: 'spell' },
  { id: 'sp_t4_3', name: '健美大赛', tier: 4, description: '获得2金币，每存在1个攻击力不低于10的友方，额外获得1金币', type: 'spell' },
  { id: 'sp_t4_4', name: '力量压制(4)', tier: 4, description: '使1个友方获得成长：+1+1', type: 'spell' },
  { id: 'sp_t4_5', name: '量产工厂(4)', tier: 4, description: '选择1个不超过2星的随从，获得1张它的原始复制', type: 'spell' },
  { id: 'sp_t4_6', name: '稳固攻击(4)', tier: 4, description: '使1个友方+8攻击', type: 'spell' },
  { id: 'sp_t4_7', name: '上发条(4)', tier: 4, description: '使商店的1个随从获得+6+6', type: 'spell' },
  { id: 'sp_t4_8', name: '理财能手(4)', tier: 4, description: '使1个友方获得成长：获得1金币', type: 'spell' },
  { id: 'sp_t4_9', name: '火球术(4)', tier: 4, description: '使1个友方获得先手：造成3点伤害', type: 'spell' },
  { id: 'sp_t4_10', name: '绝妙藏品(4)', tier: 4, description: '挑选1张3星装备牌', type: 'spell' },
  { id: 'sp_t4_11', name: '丛林探险(4)', tier: 4, description: '挑选1张3星随从', type: 'spell' },
  { id: 'sp_t4_12', name: '生命庇护(4)', tier: 4, description: '使1个友方+8生命', type: 'spell' },
  { id: 'sp_t4_13', name: '加速(4)', tier: 4, description: '触发1个友方的成长效果，并使其获得+2+2', type: 'spell' },
  { id: 'sp_t4_14', name: '女王旗帜(4)', tier: 4, description: '使3个友方各获得+2+2', type: 'spell' },
  { id: 'sp_t4_15', name: '抽奖箱', tier: 4, description: '刷新商店，并使刷出的随从属性值翻倍', type: 'spell' },
  { id: 'sp_t4_16', name: '生长(4)', tier: 4, description: '使1个友方获得成长：+3生命', type: 'spell' },
  { id: 'sp_t4_17', name: '饱食(4)', tier: 4, description: '使1个友方获得+4+4', type: 'spell' },
  { id: 'sp_t4_18', name: '贤者之石(4)', tier: 4, description: '使1个不超过2星的随从变为金色', type: 'spell' },
  { id: 'sp_t4_19', name: '精挑细选(4)', tier: 4, description: '接下来3次刷新免费', type: 'spell' },
  { id: 'sp_t4_20', name: '炸弹(4)', tier: 4, description: '使1个友方获得遗言：造成3点伤害', type: 'spell' },
  { id: 'sp_t4_21', name: '剑术训练(4)', tier: 4, description: '所有友方获得+3攻击', type: 'spell' },
  { id: 'sp_t4_22', name: '响指(4)', tier: 4, description: '召唤2个2/2的随机随从', type: 'spell' },
  { id: 'sp_t4_23', name: '法力源泉(4)', tier: 4, description: '使1个友方获得1层增伤', type: 'spell' },
  { id: 'sp_t4_24', name: '迷失森林(4)', tier: 4, description: '获得1张随机4星随从牌', type: 'spell' },
  { id: 'sp_t4_25', name: '护甲师(4)', tier: 4, description: '所有友方获得+3生命', type: 'spell' },
  { id: 'sp_t4_26', name: '激励(4)', tier: 4, description: '使1个友方获得成长：+3攻击', type: 'spell' },
  { id: 'sp_t4_27', name: '吞没(4)', tier: 4, description: '使1个友方获得击杀：永久+1+1', type: 'spell' },
  { id: 'sp_t4_28', name: '骨卜(4)', tier: 4, description: '移除1个友方，挑选1个4星随从', type: 'spell' },
  { id: 'sp_t4_29', name: '从零开始(4)', tier: 4, description: '使1个随从变为1/1并获得成长：+2+2', type: 'spell' },
  { id: 'sp_t3_30', name: '点石成金', tier: 3, description: '随机1个1星的友方变为金色', type: 'spell' },
  { id: 'sp_t3_31', name: '绝妙藏品(3)', tier: 3, description: '挑选1张2星装备牌', type: 'spell' },
  { id: 'sp_t3_32', name: '力量祝福(3)', tier: 3, description: '所有友方获得+1+1', type: 'spell' },
  { id: 'sp_t3_33', name: '丛林探险(3)', tier: 3, description: '挑选1张2星随从', type: 'spell' },
  { id: 'sp_t3_34', name: '生命庇护(3)', tier: 3, description: '使1个友方+6生命', type: 'spell' },
  { id: 'sp_t3_35', name: '骨卜(3)', tier: 3, description: '移除1个友方，挑选1个3星随从', type: 'spell' },
  { id: 'sp_t3_36', name: '护甲师(3)', tier: 3, description: '所有友方+2生命', type: 'spell' },
  { id: 'sp_t3_37', name: '量产工厂(3)', tier: 3, description: '选择1个1星的随从，获得1张它的原始复制', type: 'spell' },
  { id: 'sp_t3_38', name: '稳固攻击(3)', tier: 3, description: '使1个友方+6攻击', type: 'spell' },
  { id: 'sp_t3_39', name: '饱食(3)', tier: 3, description: '使1个友方获得+3+3', type: 'spell' },
  { id: 'sp_t3_40', name: '异变之力', tier: 3, description: '使1个随从变为+1星级的随从', type: 'spell' },
  { id: 'sp_t3_41', name: '帽子戏法(3)', tier: 3, description: '使1个随从变为6/6', type: 'spell' },
  { id: 'sp_t3_42', name: '头脑风暴(3)', tier: 3, description: '获得3点经验', type: 'spell' },
  { id: 'sp_t3_43', name: '抓钩', tier: 3, description: '挑选1个1星的随从（每回合升级）', type: 'spell' },
  { id: 'sp_t3_44', name: '剑术训练(3)', tier: 3, description: '所有友方+2攻击', type: 'spell' },
  { id: 'sp_t3_45', name: '拧紧螺栓(3)', tier: 3, description: '永久使商店所有随从获得+1+1', type: 'spell' },
  { id: 'sp_t2_46', name: '生命庇护(2)', tier: 2, description: '使1个友方+4生命', type: 'spell' },
  { id: 'sp_t2_47', name: '女王旗帜(2)', tier: 2, description: '使3个友方各获得+1+1', type: 'spell' },
  { id: 'sp_t2_48', name: '稳固攻击(2)', tier: 2, description: '使1个友方+4攻击', type: 'spell' },
  { id: 'sp_t2_49', name: '帽子戏法(2)', tier: 2, description: '使1个随从变为4/4', type: 'spell' },
  { id: 'sp_t2_50', name: '头脑风暴(2)', tier: 2, description: '获得2点经验', type: 'spell' },
  { id: 'sp_t2_51', name: '饱食(2)', tier: 2, description: '使1个友方获得+2+2', type: 'spell' },
  { id: 'sp_t2_52', name: '生长(2)', tier: 2, description: '使1个友方获得成长：+1生命', type: 'spell' },
  { id: 'sp_t2_53', name: '激励(2)', tier: 2, description: '使1个友方获得成长：+1攻击', type: 'spell' },
  { id: 'sp_t2_54', name: '上发条(2)', tier: 2, description: '使商店的1个随从获得+3+3', type: 'spell' },
  { id: 'sp_t2_55', name: '响指(2)', tier: 2, description: '召唤1个1/1的随机随从', type: 'spell' },
  { id: 'sp_t5_56', name: '饱食(5)', tier: 5, description: '使1个友方获得+6+6', type: 'spell' },
  { id: 'sp_t5_57', name: '招募强者', tier: 5, description: '刷新商店，出现3个当前等级的物品', type: 'spell' },
  { id: 'sp_t5_58', name: '发财(5)', tier: 5, description: '获得2金币，每存在1个金色友方，额外获得2金币', type: 'spell' },
  { id: 'sp_t5_59', name: '头脑风暴(5)', tier: 5, description: '获得5点经验', type: 'spell' },
  { id: 'sp_t5_60', name: '洞穴奇遇', tier: 5, description: '移除1个友方，下回合获得2张原始复制', type: 'spell' },
  { id: 'sp_t5_61', name: '量产工厂(5)', tier: 5, description: '选择1个不超过3星的随从，获得1张它的原始复制', type: 'spell' },
  { id: 'sp_t5_62', name: '不稳定克隆', tier: 5, description: '移除1个友方，获得2张相同星级的随机随从牌', type: 'spell' },
  { id: 'sp_t5_63', name: '绝妙藏品(5)', tier: 5, description: '挑选1张4星装备牌', type: 'spell' },
  { id: 'sp_t5_64', name: '力量祝福(5)', tier: 5, description: '所有友方获得+2+2', type: 'spell' },
  { id: 'sp_t5_65', name: '挖掘宝物', tier: 5, description: '使1个友方获得：攻击时，获得1金币', type: 'spell' },
  { id: 'sp_t5_66', name: '吸尘器', tier: 5, description: '使1个友方吸取其他友方一半属性值', type: 'spell' },
  { id: 'sp_t5_67', name: '丛林探险(5)', tier: 5, description: '挑选1张4星随从', type: 'spell' },
  { id: 'sp_t5_68', name: '雕像', tier: 5, description: '使1个随从获得无法攻击，然后使所有无法攻击的友方+2+4', type: 'spell' },
  { id: 'sp_t5_69', name: '拧紧螺栓(5)', tier: 5, description: '永远使商店所有随从获得+3+3', type: 'spell' },
  { id: 'sp_t5_70', name: '恶魔天平', tier: 5, description: '移除1个随从，第1个友方获得其属性值', type: 'spell' },
  { id: 'sp_t5_71', name: '护甲师(5)', tier: 5, description: '所有友方+4生命', type: 'spell' },
  { id: 'sp_t6_72', name: '捡漏', tier: 6, description: '获得当前商店的所有卡牌', type: 'spell' },
  { id: 'sp_t5_73', name: '贤者之石(5)', tier: 5, description: '使1个不超过3星的随从变为金色', type: 'spell' },
  { id: 'sp_t5_74', name: '精挑细选(5)', tier: 5, description: '接下来4次刷新免费', type: 'spell' },
  { id: 'sp_t5_75', name: '剑术训练(5)', tier: 5, description: '所有友方+4攻击', type: 'spell' },
  { id: 'sp_t5_76', name: '迷失森林(5)', tier: 5, description: '获得1张随机5星随从牌', type: 'spell' },
  { id: 'sp_t5_77', name: '三头六臂', tier: 5, description: '获得1张友方类型的随机附着牌', type: 'spell' },
  { id: 'sp_t5_78', name: '巧夺', tier: 5, description: '挑选你上个对手的1个随从的原始复制', type: 'spell' },
  { id: 'sp_t5_79', name: '加速(5)', tier: 5, description: '触发1个友方的成长效果，并使其获得+4+4', type: 'spell' },
  { id: 'sp_t5_80', name: '从零开始(5)', tier: 5, description: '使1个随从变为1/1并获得成长：+3+3', type: 'spell' },
  { id: 'sp_t5_81', name: '最后的希望', tier: 5, description: '用随机随从填满你的战场', type: 'spell' },
  { id: 'sp_t6_82', name: '法力源泉(6)', tier: 6, description: '使1个友方获得2层增伤', type: 'spell' },
  { id: 'sp_t6_83', name: '精挑细选(6)', tier: 6, description: '接下来5次刷新免费', type: 'spell' },
  { id: 'sp_t6_84', name: '火球术(6)', tier: 6, description: '使1个友方获得先手：造成3点伤害2次', type: 'spell' },
  { id: 'sp_t6_85', name: '量身定做', tier: 6, description: '使1个友方获得1个装备槽', type: 'spell' },
  { id: 'sp_t6_86', name: '拍卖会', tier: 6, description: '本回合卖出卡牌额外获得1金币', type: 'spell' },
  { id: 'sp_t6_87', name: '量产工厂(6)', tier: 6, description: '选择1个不超过4星的随从，获得1张它的原始复制', type: 'spell' },
  { id: 'sp_t6_88', name: '炸弹(6)', tier: 6, description: '使1个友方获得遗言：造成3点伤害2次', type: 'spell' },
  { id: 'sp_t6_89', name: '力量压制(6)', tier: 6, description: '使1个友方获得成长：+2+2', type: 'spell' },
  { id: 'sp_t6_90', name: '发财(6)', tier: 6, description: '获得3金币，每存在1个金色友方，额外获得2金币', type: 'spell' },
  { id: 'sp_t6_91', name: '饱食(6)', tier: 6, description: '使1个友方获得+9+9', type: 'spell' },
  { id: 'sp_t6_92', name: '丛林探险(6)', tier: 6, description: '挑选1张5星随从', type: 'spell' },
  { id: 'sp_t6_93', name: '卡牌包', tier: 6, description: '随机获得1-2星、3-4、5-6星随从各一张', type: 'spell' },
  { id: 'sp_t6_94', name: '血瓶', tier: 6, description: '英雄每已损失1生命，使1个友方+1生命', type: 'spell' },
  { id: 'sp_t6_95', name: '绝妙藏品(6)', tier: 6, description: '挑选1张5星装备牌', type: 'spell' },
  { id: 'sp_t6_96', name: '神圣祝福', tier: 6, description: '使1个友方获得护盾', type: 'spell' },
  { id: 'sp_t6_97', name: '魔术怀表', tier: 6, description: '触发所有友方的成长效果', type: 'spell' },
  { id: 'sp_t6_98', name: '鬼牌', tier: 6, description: '获得左边手牌的原始复制', type: 'spell' },
  { id: 'sp_t6_99', name: '吞没(6)', tier: 6, description: '使1个友方获得击杀：永久+2+2', type: 'spell' },
  { id: 'sp_t6_100', name: '命悬一线', tier: 6, description: '将你的生命值变为1，获得16金币', type: 'spell' },
  { id: 'sp_t6_101', name: '理财能手(6)', tier: 6, description: '使1个友方获得成长：获得2金币', type: 'spell' },
  { id: 'sp_t6_102', name: '千刀万剐', tier: 6, description: '使1个友方获得疯狂', type: 'spell' },
  { id: 'sp_t2_103', name: '许愿', tier: 2, description: '将商店1个随从变形为+1星随从', type: 'spell' },
  { id: 'sp_t2_104', name: '上锁的日记(2)', tier: 2, description: '在升级到4星后才能使用，挑选1张4星咒术', type: 'spell' },
  { id: 'sp_t3_105', name: '上锁的日记(3)', tier: 3, description: '在升级到5星后才能使用，挑选1张5星咒术', type: 'spell' },
  { id: 'sp_t3_106', name: '抽奖', tier: 3, description: '随机获得商店1张牌', type: 'spell' },
  { id: 'sp_t4_107', name: '吹嘘', tier: 4, description: '获得1张随机入场', type: 'spell' },
  { id: 'sp_t5_108', name: '剑术陪练', tier: 5, description: '使商店1个随从属性值翻倍', type: 'spell' },
  { id: 'sp_t5_109', name: '命悬一线(5)', tier: 5, description: '将你的生命值变为1，获得12金币', type: 'spell' },
  { id: 'sp_t5_110', name: '考古学', tier: 5, description: '选择1个友方，挑选1张其阵营的随从牌', type: 'spell' },
  { id: 'sp_t5_111', name: '原始法则', tier: 5, description: '使一个友方获得攻击力或者生命，直到2者相等', type: 'spell' },
  { id: 'sp_t6_112', name: '许愿神灯', tier: 6, description: '挑选1张咒术牌，下回合获得1张许愿神灯', type: 'spell' },
];

export const SPELLS_BY_TIER = {
  1: SPELLS.filter(s => s.tier === 1),
  2: SPELLS.filter(s => s.tier === 2),
  3: SPELLS.filter(s => s.tier === 3),
  4: SPELLS.filter(s => s.tier === 4),
  5: SPELLS.filter(s => s.tier === 5),
  6: SPELLS.filter(s => s.tier === 6),
};
